version: "3.8"

services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:14.6-alpine
    env_file: ./config/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      timeout: 5s
      interval: 30s
      retries: 3
    restart: unless-stopped
    ports:
      - "5433:5432"
  api:
    hostname: api
    container_name: "api"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0  --port 8080"

    restart: unless-stopped

volumes:
  postgres_data:
